### ISSUE TITLE
On http server module

### ISSUE THREAD

**Issue by BenLaylor269** [WhineyMonkey10/random_profile_generator#5]
I would recommend that you replace `http.server` with flask. Flask is more standard, and http.server is not supposed to be used for production purposes according to its website https://docs.python.org/3/library/http.server.html.
I would be glad to help you translate your code to flask when I have time.
In the mean time I would recommend you read the flask guide https://flask.palletsprojects.com/en/2.1.x/quickstart/#a-minimal-application.

**Comment by WhineyMonkey10** [comment]
Hey there @BenLaylor269 !

Thanks for pointing this out, at the time, I was deciding whether or not to use flask and decided to use an http server since I thought it would be simpler. Although, as you pointed out, it's not really production based which I didn't see. Also, the local server is not fully finished yet, so I'll most likely switch over to flask.

Thanks,
WhineyMonkey10
